# Generated by Django 4.1 on 2022-08-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomcode', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KirrURL',
        ),
    ]
